// Granel Movimientos Data Source (Auto-updated: 2026-08-24 17:39:30)
window.GRANEL_DATA = {
    kpis: {
        comprasLitros: 0.0,
        ventasLitros: 3796.8,
        stockSaldoLitros: -3796.8,
        extraccionesLitros: 9017.0,
        montoCompras: 0.0,
        montoVentas: 2665204.0,
        guiasEnap: 6,
        ventasOps: 10,
        extraccionesOps: 17,
        comisionesPagadas: 0.0,
        comisionesPendientes: 2884800.0,
        totalComisiones: 2884800.0,
        costoPromedioLitro: 336.77,
        precioPromedioVentaLitro: 701.96,
        margenPromedioLitro: 365.19,
        porcentajeMargenBruto: 52.0,
        camionVJYL61Ops: 28,
        camionVJYL42Ops: 5
    },
    transacciones: [
    {
        "fecha": "2026-07-23",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3836889"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "1403",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ricardo Brisas del Raco",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del Raco",
        "precio": 1000.0,
        "litros": 179.2,
        "total": 179200.0,
        "medioPago": "N/A",
        "comision": 179200.0,
        "observacion": "Tarjeta",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ale Turko",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 518.1,
        "total": 518100.0,
        "medioPago": "N/A",
        "comision": 518100.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Tirua",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 488.2,
        "total": 488200.0,
        "medioPago": "N/A",
        "comision": 488200.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ciao Italia",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 500.3,
        "total": 500300.0,
        "medioPago": "N/A",
        "comision": 500300.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Claudio Ulloa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 237.9,
        "total": 237900.0,
        "medioPago": "N/A",
        "comision": 237900.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Francisco Ulloa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 205.1,
        "total": 205100.0,
        "medioPago": "N/A",
        "comision": 205100.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Alicia Pavez",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 300.0,
        "total": 300000.0,
        "medioPago": "N/A",
        "comision": 300000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Vanessa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 200.0,
        "total": 200000.0,
        "medioPago": "N/A",
        "comision": 200000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Franco Garcia",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Santa Rita 1177 parcela 14 Pirque",
        "precio": 0.0,
        "litros": 912.0,
        "total": 13789.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-07-30",
        "cliente": "Simon",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino el Chalaco 66B",
        "precio": 1000.0,
        "litros": 747.0,
        "total": 14535.0,
        "medioPago": "N/A",
        "comision": 747000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Manuel Vergara Ricci",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Avenida Virginia subercaseaux 4175 (parcela 15)",
        "precio": 1100.0,
        "litros": 200.0,
        "total": 14735.0,
        "medioPago": "N/A",
        "comision": 220000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Gabriela Rojas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino de las flores 1262 Pirque",
        "precio": 1100.0,
        "litros": 350.0,
        "total": 16490.0,
        "medioPago": "N/A",
        "comision": 385000.0,
        "observacion": "Transferencia en dos",
        "detalles": ""
    },
    {
        "fecha": "2026-08-04",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "1403",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-05",
        "cliente": "Casa de Reposo Brisas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del raco parcela 36 Pirque",
        "precio": 1100.0,
        "litros": 270.0,
        "total": 16760.0,
        "medioPago": "N/A",
        "comision": 297000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Gastronomca Exquisite",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "JP Alesaandri 114 Nuñoa",
        "precio": 1000.0,
        "litros": 350.0,
        "total": 17110.0,
        "medioPago": "N/A",
        "comision": 350000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Panaderia Maipu",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Av los carreras 706B, plaza de los porotos",
        "precio": 1000.0,
        "litros": 109.0,
        "total": 17219.0,
        "medioPago": "N/A",
        "comision": 109000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-08",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "2219",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Eli Ciao Italia",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino rinconada san Vicente parcela 38",
        "precio": 1100.0,
        "litros": 404.0,
        "total": 19834.0,
        "medioPago": "N/A",
        "comision": 444400.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Javier Quiroz",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Condominio majadas C parcela 5",
        "precio": 1100.0,
        "litros": 509.0,
        "total": 20343.0,
        "medioPago": "N/A",
        "comision": 559900.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-12",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3882182"
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "11539",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-13",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3836889"
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Mister Guss SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "PRIMERA TRANSVERSAL 828 PADRE HURTADO",
        "precio": 1000.0,
        "litros": 256.0,
        "total": 22615.0,
        "medioPago": "N/A",
        "comision": 256000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-14",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3955528"
    },
    {
        "fecha": "2026-08-18",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3889821"
    },
    {
        "fecha": "2026-08-19",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 0.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "ENAP carga",
        "detalles": "3830686"
    },
    {
        "fecha": "2026-08-20",
        "cliente": "Bar Barrio Alto",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "El Peñón 335 Puente Alto",
        "precio": 1000.0,
        "litros": 294.0,
        "total": 22909.0,
        "medioPago": "N/A",
        "comision": 294000.0,
        "observacion": "Transferencia dos",
        "detalles": ""
    },
    {
        "fecha": "2026-08-20",
        "cliente": "BAR Tirua",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Pirque",
        "precio": 1100.0,
        "litros": 500.0,
        "total": 23409.0,
        "medioPago": "N/A",
        "comision": 550000.0,
        "observacion": "Pendiente de pago",
        "detalles": ""
    },
    {
        "fecha": "2026-08-20",
        "cliente": "Brasas y Sabor SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Puente Alto",
        "precio": 1100.0,
        "litros": 100.0,
        "total": 23509.0,
        "medioPago": "N/A",
        "comision": 110000.0,
        "observacion": "Transferencia",
        "detalles": ""
    },
    {
        "fecha": "2026-08-24",
        "cliente": "Franco Garcia",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Santa Rita 1177 parcela 14 Pirque",
        "precio": 0.0,
        "litros": 1120.0,
        "total": 24630.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-24",
        "cliente": "Centro de Eventos Barrio Alto SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "El Peñón 335 Puente Alto",
        "precio": 1000.0,
        "litros": 449.0,
        "total": 25078.0,
        "medioPago": "N/A",
        "comision": 449000.0,
        "observacion": "Transferencia",
        "detalles": ""
    }
]
};
