// Granel Movimientos Data Source (Auto-updated: 2026-08-14 14:21:23)
window.GRANEL_DATA = {
    kpis: {
        comprasLitros: 46235.0,
        ventasLitros: 6735.8,
        stockSaldoLitros: 39499.2,
        extraccionesLitros: 16564.0,
        montoCompras: 15451082.0,
        montoVentas: 5997100.0,
        comisionesPagadas: 485760,
        comisionesPendientes: 536000,
        totalComisiones: 1021760,
        costoPromedioLitro: 334.19,
        precioPromedioVentaLitro: 890.33,
        margenPromedioLitro: 556.15,
        porcentajeMargenBruto: 62.5
    },
    transacciones: [
    {
        "fecha": "2026-07-23",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Guía N° xxxxx"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 1403.0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Extraccion"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ricardo Brisas del Raco",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del Raco",
        "precio": 1000.0,
        "litros": 179.2,
        "total": 179200.0,
        "medioPago": "179200",
        "comision": 0,
        "observacion": "35840",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ale Turko",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 518.1,
        "total": 518100.0,
        "medioPago": "518100",
        "comision": 0,
        "observacion": "103620",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Tirua ",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 488.2,
        "total": 488200.0,
        "medioPago": "488200",
        "comision": 0,
        "observacion": "97640",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ciao Italia ",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 500.3,
        "total": 500300.0,
        "medioPago": "500300",
        "comision": 0,
        "observacion": "100060",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Claudio Ulloa ",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 237.9,
        "total": 237900.0,
        "medioPago": "237900",
        "comision": 0,
        "observacion": "47580",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Francisco Ulloa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 205.1,
        "total": 205100.0,
        "medioPago": "205100",
        "comision": 0,
        "observacion": "41020",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Alicia Pavez",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 300.0,
        "total": 300000.0,
        "medioPago": "300000",
        "comision": 0,
        "observacion": "60000",
        "detalles": "Comision Pagada"
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Vanessa ",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 200.0,
        "total": 200000.0,
        "medioPago": "200000",
        "comision": 0,
        "observacion": "40000",
        "detalles": ""
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Franco Garcia",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Santa Rita 1177 parcela 14 Pirque",
        "precio": 0.0,
        "litros": 912.0,
        "total": 0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-07-30",
        "cliente": "Simon",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino el Chalaco 66B",
        "precio": 1000.0,
        "litros": 747.0,
        "total": 747000.0,
        "medioPago": "747000",
        "comision": 0,
        "observacion": "149400",
        "detalles": "Factura"
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Manuel Vergara Ricci",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Avenida Virginia subercaseaux 4175 (parcela 15)",
        "precio": 1100.0,
        "litros": 200.0,
        "total": 220000.0,
        "medioPago": "220000",
        "comision": 0,
        "observacion": "40000",
        "detalles": ""
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Gabriela Rojas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino de las flores 1262 Pirque",
        "precio": 1100.0,
        "litros": 350.0,
        "total": 385000.0,
        "medioPago": "385000",
        "comision": 0,
        "observacion": "70000",
        "detalles": "Quedó saldo de $35 mil para mañana"
    },
    {
        "fecha": "2026-08-04",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 1403.0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Extraccion"
    },
    {
        "fecha": "2026-08-05",
        "cliente": "Casa de Reposo Brisas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del raco parcela 36 Pirque",
        "precio": 1100.0,
        "litros": 270.0,
        "total": 297000.0,
        "medioPago": "297000",
        "comision": 0,
        "observacion": "54000",
        "detalles": "Factura"
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Gastronomca Exquisite",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "JP Alesaandri 114 Nuñoa",
        "precio": 1000.0,
        "litros": 350.0,
        "total": 350000.0,
        "medioPago": "350000",
        "comision": 0,
        "observacion": "",
        "detalles": "Factura"
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Panaderia Maipu",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Av los carreras 706B, plaza de los porotos",
        "precio": 1000.0,
        "litros": 109.0,
        "total": 109000.0,
        "medioPago": "109000",
        "comision": 0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-08",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 2219.0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Extraccion"
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Eli Ciao Italia",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino rinconada san Vicente parcela 38",
        "precio": 1100.0,
        "litros": 404.0,
        "total": 444400.0,
        "medioPago": "444400",
        "comision": 0,
        "observacion": "80800",
        "detalles": ""
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Javier Quiroz",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Condominio majadas C parcela 5",
        "precio": 1100.0,
        "litros": 509.0,
        "total": 559900.0,
        "medioPago": "559900",
        "comision": 0,
        "observacion": "101800",
        "detalles": ""
    },
    {
        "fecha": "2026-08-12",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Guía N° 2356186"
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 11539.0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Extraccion"
    },
    {
        "fecha": "2026-08-13",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Guía N° 2356453"
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Mister Guss SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "PRIMERA TRANSVERSAL 828 PADRE HURTADO",
        "precio": 1000.0,
        "litros": 256.0,
        "total": 256000.0,
        "medioPago": "256000",
        "comision": 0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-14",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0,
        "litros": 0,
        "total": 0,
        "medioPago": "N/A",
        "comision": 0,
        "observacion": "",
        "detalles": "Guía N° 2356889"
    }
]
};
