// Granel Movimientos Data Source (Auto-updated: 2026-08-26 23:48:22)
window.GRANEL_DATA = {
    kpis: {
        comprasLitros: 90961.0,
        ventasLitros: 9198.8,
        stockSaldoLitros: 31541.199999999997,
        extraccionesLitros: 50221.0,
        montoCompras: 30575790.0,
        montoVentas: 7400100.0,
        guiasEnap: 8,
        ventasOps: 23,
        extraccionesOps: 7,
        comisionesPagadas: 485760.0,
        comisionesPendientes: 694800.0,
        totalComisiones: 1180560.0,
        costoPromedioLitro: 336.14,
        precioPromedioVentaLitro: 804.46,
        margenPromedioLitro: 468.32,
        porcentajeMargenBruto: 58.2,
        camionVJYL61Ops: 28,
        camionVJYL42Ops: 10
    },
    transacciones: [
    {
        "fecha": "2026-07-23",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11481.0,
        "total": 3836889.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° xxxxx",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 1403.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ricardo Brisas del Raco",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del Raco",
        "precio": 1000.0,
        "litros": 179.2,
        "total": 179200.0,
        "medioPago": "Tarjeta",
        "comision": 35840.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ale Turko",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 518.1,
        "total": 518100.0,
        "medioPago": "Pendiente de pago",
        "comision": 103620.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Tirua",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 488.2,
        "total": 488200.0,
        "medioPago": "Pendiente de pago",
        "comision": 97640.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Ciao Italia",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 500.3,
        "total": 500300.0,
        "medioPago": "Pendiente de pago",
        "comision": 100060.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Claudio Ulloa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 237.9,
        "total": 237900.0,
        "medioPago": "Pendiente de pago",
        "comision": 47580.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Francisco Ulloa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 205.1,
        "total": 205100.0,
        "medioPago": "Pendiente de pago",
        "comision": 41020.0,
        "observacion": "Comision Pagada",
        "detalles": ""
    },
    {
        "fecha": "2026-07-27",
        "cliente": "Alicia Pavez",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 300.0,
        "total": 300000.0,
        "medioPago": "Transferencia",
        "comision": 60000.0,
        "observacion": "Comision Pagada",
        "detalles": "2428.8"
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Vanessa",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "N/A",
        "precio": 1000.0,
        "litros": 200.0,
        "total": 200000.0,
        "medioPago": "Transferencia",
        "comision": 40000.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-07-28",
        "cliente": "Franco Garcia",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Santa Rita 1177 parcela 14 Pirque",
        "precio": 0.0,
        "litros": 912.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-07-30",
        "cliente": "Simon",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino el Chalaco 66B",
        "precio": 1000.0,
        "litros": 747.0,
        "total": 747000.0,
        "medioPago": "Transferencia",
        "comision": 149400.0,
        "observacion": "Factura",
        "detalles": "Ebal spa - RUT: 77.625.623-4 - Av Gabriela 3264 La Pintana - Giro Construccion"
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Manuel Vergara Ricci",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Avenida Virginia subercaseaux 4175 (parcela 15)",
        "precio": 1100.0,
        "litros": 200.0,
        "total": 220000.0,
        "medioPago": "Transferencia",
        "comision": 40000.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-03",
        "cliente": "Gabriela Rojas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino de las flores 1262 Pirque",
        "precio": 1100.0,
        "litros": 350.0,
        "total": 385000.0,
        "medioPago": "Transferencia en dos",
        "comision": 70000.0,
        "observacion": "Quedó saldo de $35 mil para mañana",
        "detalles": ""
    },
    {
        "fecha": "2026-08-04",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 1403.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-05",
        "cliente": "Casa de Reposo Brisas",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Brisas del raco parcela 36 Pirque",
        "precio": 1100.0,
        "litros": 270.0,
        "total": 297000.0,
        "medioPago": "Transferencia",
        "comision": 54000.0,
        "observacion": "Factura",
        "detalles": "Residencia Adulto Mayor Amor Eterno SpA - Rut 76.699.397-4 - Los Almendros Parcela2B Pirque"
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Gastronomca Exquisite",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "JP Alesaandri 114 Nuñoa",
        "precio": 1000.0,
        "litros": 350.0,
        "total": 350000.0,
        "medioPago": "Transferencia",
        "comision": 0.0,
        "observacion": "Factura",
        "detalles": "Gastronomica Exquisite SpA - Rut: 77.714.318-2 - JP alessandri 114 Nuñoa"
    },
    {
        "fecha": "2026-08-07",
        "cliente": "Panaderia Maipu",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Av los carreras 706B, plaza de los porotos",
        "precio": 1000.0,
        "litros": 109.0,
        "total": 109000.0,
        "medioPago": "Transferencia",
        "comision": 0.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-08",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL61",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 2219.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Eli Ciao Italia",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Camino rinconada san Vicente parcela 38",
        "precio": 1100.0,
        "litros": 404.0,
        "total": 444400.0,
        "medioPago": "Transferencia",
        "comision": 80800.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-11",
        "cliente": "Javier Quiroz",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Condominio majadas C parcela 5",
        "precio": 1100.0,
        "litros": 509.0,
        "total": 559900.0,
        "medioPago": "Transferencia",
        "comision": 101800.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-12",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11617.0,
        "total": 3882182.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2356186",
        "detalles": ""
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11539.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-13",
        "cliente": "ENAP carga",
        "camion": "VJYL61",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11481.0,
        "total": 3836889.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2356453",
        "detalles": ""
    },
    {
        "fecha": "2026-08-13",
        "cliente": "Mister Guss SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "PRIMERA TRANSVERSAL 828 PADRE HURTADO",
        "precio": 1000.0,
        "litros": 256.0,
        "total": 256000.0,
        "medioPago": "Transferencia",
        "comision": 0.0,
        "observacion": "Factura",
        "detalles": "MISTER GUSS SPA - RUT 78.060.801-3 - PRIMERA TRANSVERSAL 828 PADRE HURTADO - RESTOBAR"
    },
    {
        "fecha": "2026-08-14",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11656.0,
        "total": 3955528.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2356889",
        "detalles": ""
    },
    {
        "fecha": "2026-08-17",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11344.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-18",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11462.0,
        "total": 3889821.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2358078",
        "detalles": ""
    },
    {
        "fecha": "2026-08-19",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11288.0,
        "total": 3830686.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2358522",
        "detalles": ""
    },
    {
        "fecha": "2026-08-19",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11225.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-20",
        "cliente": "Ignacio Guerrero",
        "camion": "VJYL42",
        "vendedor": "Ignacio",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11088.0,
        "total": 0.0,
        "medioPago": "Extraccion",
        "comision": 0.0,
        "observacion": "Extraccion",
        "detalles": ""
    },
    {
        "fecha": "2026-08-20",
        "cliente": "Bar Barrio Alto",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "El Peñón 335 Puente Alto",
        "precio": 1000.0,
        "litros": 294.0,
        "total": 294000.0,
        "medioPago": "Transferencia dos",
        "comision": 58800.0,
        "observacion": "Factura",
        "detalles": "Centro de eventos Barrio Alto SpA - RUT 78.467.844-K - EL PENON CHICO 0335 PUENTE ALTO"
    },
    {
        "fecha": "2026-08-20",
        "cliente": "BAR Tirua",
        "camion": "VJYL61",
        "vendedor": "CJ",
        "direccion": "Pirque",
        "precio": 1100.0,
        "litros": 500.0,
        "total": 550000.0,
        "medioPago": "Pendiente de pago",
        "comision": 100000.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-20",
        "cliente": "Brasas y Sabor SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Puente Alto",
        "precio": 1100.0,
        "litros": 100.0,
        "total": 110000.0,
        "medioPago": "Transferencia",
        "comision": 0.0,
        "observacion": "Factura",
        "detalles": "Brasas y Sabor SpA - RUT 76.378-704-4 - Av Concha y Toro #11 Puente Alto"
    },
    {
        "fecha": "2026-08-24",
        "cliente": "Franco Garcia",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "Santa Rita 1177 parcela 14 Pirque",
        "precio": 0.0,
        "litros": 1120.0,
        "total": 0.0,
        "medioPago": "N/A",
        "comision": 0.0,
        "observacion": "",
        "detalles": ""
    },
    {
        "fecha": "2026-08-24",
        "cliente": "Centro de Eventos Barrio Alto SpA",
        "camion": "VJYL61",
        "vendedor": "Tripulacion",
        "direccion": "El Peñón 335 Puente Alto",
        "precio": 1000.0,
        "litros": 449.0,
        "total": 449000.0,
        "medioPago": "Transferencia",
        "comision": 0.0,
        "observacion": "Factura",
        "detalles": "Centro de eventos Barrio Alto SpA - RUT 78.467.844-K - EL PENON CHICO 0335 PUENTE ALTO"
    },
    {
        "fecha": "2026-08-25",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 11288.0,
        "total": 3772187.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2360214",
        "detalles": ""
    },
    {
        "fecha": "2026-08-26",
        "cliente": "ENAP carga",
        "camion": "VJYL42",
        "vendedor": "ENAP carga",
        "direccion": "N/A",
        "precio": 0.0,
        "litros": 10688.0,
        "total": 3571608.0,
        "medioPago": "ENAP carga",
        "comision": 0.0,
        "observacion": "Guía N° 2360596",
        "detalles": ""
    }
]
};
